# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/hw_acc/hw_acc.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_acc || ORIG_REF_NAME==hw_acc} -quiet] -quiet

# IP: bd/hw_acc/ip/hw_acc_processing_system7_0_0/hw_acc_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_acc_processing_system7_0_0 || ORIG_REF_NAME==hw_acc_processing_system7_0_0} -quiet] -quiet

# IP: bd/hw_acc/ip/hw_acc_sha256_0_0/hw_acc_sha256_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_acc_sha256_0_0 || ORIG_REF_NAME==hw_acc_sha256_0_0} -quiet] -quiet

# IP: bd/hw_acc/ip/hw_acc_ps7_0_axi_periph_0/hw_acc_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_acc_ps7_0_axi_periph_0 || ORIG_REF_NAME==hw_acc_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/hw_acc/ip/hw_acc_rst_ps7_0_100M_0/hw_acc_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_acc_rst_ps7_0_100M_0 || ORIG_REF_NAME==hw_acc_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/hw_acc/ip/hw_acc_axi_intc_0_0/hw_acc_axi_intc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_acc_axi_intc_0_0 || ORIG_REF_NAME==hw_acc_axi_intc_0_0} -quiet] -quiet

# IP: bd/hw_acc/ip/hw_acc_xbar_0/hw_acc_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_acc_xbar_0 || ORIG_REF_NAME==hw_acc_xbar_0} -quiet] -quiet

# IP: bd/hw_acc/ip/hw_acc_auto_pc_0/hw_acc_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hw_acc_auto_pc_0 || ORIG_REF_NAME==hw_acc_auto_pc_0} -quiet] -quiet

# XDC: bd/hw_acc/hw_acc_ooc.xdc
