// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="sha256,hls_ip_2017_4,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.522000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=12,HLS_SYN_DSP=0,HLS_SYN_FF=4411,HLS_SYN_LUT=6595}" *)

module sha256 (
        ap_clk,
        ap_rst_n,
        s_axi_AXILiteS_AWVALID,
        s_axi_AXILiteS_AWREADY,
        s_axi_AXILiteS_AWADDR,
        s_axi_AXILiteS_WVALID,
        s_axi_AXILiteS_WREADY,
        s_axi_AXILiteS_WDATA,
        s_axi_AXILiteS_WSTRB,
        s_axi_AXILiteS_ARVALID,
        s_axi_AXILiteS_ARREADY,
        s_axi_AXILiteS_ARADDR,
        s_axi_AXILiteS_RVALID,
        s_axi_AXILiteS_RREADY,
        s_axi_AXILiteS_RDATA,
        s_axi_AXILiteS_RRESP,
        s_axi_AXILiteS_BVALID,
        s_axi_AXILiteS_BREADY,
        s_axi_AXILiteS_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;
parameter    C_S_AXI_AXILITES_DATA_WIDTH = 32;
parameter    C_S_AXI_AXILITES_ADDR_WIDTH = 10;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_AXILITES_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   s_axi_AXILiteS_AWVALID;
output   s_axi_AXILiteS_AWREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1:0] s_axi_AXILiteS_AWADDR;
input   s_axi_AXILiteS_WVALID;
output   s_axi_AXILiteS_WREADY;
input  [C_S_AXI_AXILITES_DATA_WIDTH - 1:0] s_axi_AXILiteS_WDATA;
input  [C_S_AXI_AXILITES_WSTRB_WIDTH - 1:0] s_axi_AXILiteS_WSTRB;
input   s_axi_AXILiteS_ARVALID;
output   s_axi_AXILiteS_ARREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1:0] s_axi_AXILiteS_ARADDR;
output   s_axi_AXILiteS_RVALID;
input   s_axi_AXILiteS_RREADY;
output  [C_S_AXI_AXILITES_DATA_WIDTH - 1:0] s_axi_AXILiteS_RDATA;
output  [1:0] s_axi_AXILiteS_RRESP;
output   s_axi_AXILiteS_BVALID;
input   s_axi_AXILiteS_BREADY;
output  [1:0] s_axi_AXILiteS_BRESP;
output   interrupt;

reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
reg   [7:0] data_address0;
reg    data_ce0;
wire   [7:0] data_q0;
wire   [31:0] base_offset;
wire   [31:0] bytes;
wire   [4:0] digest_address0;
reg    digest_ce0;
reg    digest_we0;
reg   [31:0] reg_457;
wire    ap_CS_fsm_state2;
wire   [0:0] tmp_s_fu_595_p2;
wire    ap_CS_fsm_state3;
wire   [0:0] exitcond5_fu_621_p2;
reg   [31:0] reg_463;
reg   [31:0] reg_469;
reg   [31:0] reg_475;
reg   [31:0] reg_481;
reg   [31:0] reg_487;
reg   [31:0] reg_493;
reg   [31:0] reg_499;
reg   [31:0] reg_505;
reg   [31:0] reg_511;
reg   [31:0] reg_517;
wire   [9:0] tmp_fu_523_p1;
reg   [9:0] tmp_reg_831;
reg   [31:0] n_load_reg_837;
wire   [0:0] icmp_fu_611_p2;
reg   [0:0] icmp_reg_847;
wire   [9:0] tmp_125_fu_617_p1;
reg   [9:0] tmp_125_reg_851;
wire   [6:0] i_7_fu_627_p2;
reg   [6:0] i_7_reg_860;
wire   [5:0] i_8_fu_687_p2;
reg   [5:0] i_8_reg_873;
wire    ap_CS_fsm_state6;
wire   [0:0] exitcond4_fu_682_p2;
reg   [31:0] sha256ctx_datalen_lo_1_reg_883;
reg   [31:0] sha256ctx_bitlen_0_1_reg_888;
reg   [31:0] sha256ctx_bitlen_1_1_reg_893;
reg   [31:0] sha256ctx_state_0_2_2_reg_898;
reg   [31:0] sha256ctx_state_1_2_2_reg_903;
reg   [31:0] sha256ctx_state_2_2_2_reg_908;
reg   [31:0] sha256ctx_state_3_2_2_reg_913;
reg   [31:0] sha256ctx_state_4_2_2_reg_918;
reg   [31:0] sha256ctx_state_5_2_2_reg_923;
reg   [31:0] sha256ctx_state_6_2_2_reg_928;
reg   [31:0] sha256ctx_state_7_2_2_reg_933;
wire   [5:0] i_fu_728_p2;
reg   [5:0] i_reg_941;
wire    ap_CS_fsm_state9;
wire   [63:0] tmp_114_fu_734_p1;
reg   [63:0] tmp_114_reg_946;
wire   [0:0] exitcond_fu_722_p2;
reg   [5:0] seg_buf_address0;
reg    seg_buf_ce0;
reg    seg_buf_we0;
reg   [7:0] seg_buf_d0;
wire   [7:0] seg_buf_q0;
reg    seg_buf_ce1;
reg    seg_buf_we1;
reg   [5:0] sha256ctx_data_address0;
reg    sha256ctx_data_ce0;
reg    sha256ctx_data_we0;
reg   [7:0] sha256ctx_data_d0;
wire   [7:0] sha256ctx_data_q0;
reg   [5:0] sha256ctx_data_address1;
reg    sha256ctx_data_ce1;
reg    sha256ctx_data_we1;
wire   [7:0] sha256ctx_data_q1;
wire    grp_sha256_final_fu_260_ap_start;
wire    grp_sha256_final_fu_260_ap_done;
wire    grp_sha256_final_fu_260_ap_idle;
wire    grp_sha256_final_fu_260_ap_ready;
wire   [5:0] grp_sha256_final_fu_260_ctx_data_address0;
wire    grp_sha256_final_fu_260_ctx_data_ce0;
wire    grp_sha256_final_fu_260_ctx_data_we0;
wire   [7:0] grp_sha256_final_fu_260_ctx_data_d0;
wire   [5:0] grp_sha256_final_fu_260_ctx_data_address1;
wire    grp_sha256_final_fu_260_ctx_data_ce1;
wire    grp_sha256_final_fu_260_ctx_data_we1;
wire   [7:0] grp_sha256_final_fu_260_ctx_data_d1;
wire   [5:0] grp_sha256_final_fu_260_hash_address0;
wire    grp_sha256_final_fu_260_hash_ce0;
wire    grp_sha256_final_fu_260_hash_we0;
wire   [7:0] grp_sha256_final_fu_260_hash_d0;
wire   [5:0] grp_sha256_final_fu_260_hash_address1;
wire    grp_sha256_final_fu_260_hash_ce1;
wire    grp_sha256_final_fu_260_hash_we1;
wire   [7:0] grp_sha256_final_fu_260_hash_d1;
wire    grp_sha256_update_fu_279_ap_start;
wire    grp_sha256_update_fu_279_ap_done;
wire    grp_sha256_update_fu_279_ap_idle;
wire    grp_sha256_update_fu_279_ap_ready;
wire   [5:0] grp_sha256_update_fu_279_ctx_data_address0;
wire    grp_sha256_update_fu_279_ctx_data_ce0;
wire    grp_sha256_update_fu_279_ctx_data_we0;
wire   [7:0] grp_sha256_update_fu_279_ctx_data_d0;
wire   [5:0] grp_sha256_update_fu_279_ctx_data_address1;
wire    grp_sha256_update_fu_279_ctx_data_ce1;
reg   [31:0] grp_sha256_update_fu_279_ctx_datalen_read;
reg   [31:0] grp_sha256_update_fu_279_p_read1;
reg   [31:0] grp_sha256_update_fu_279_p_read2;
reg   [31:0] grp_sha256_update_fu_279_p_read3;
reg   [31:0] grp_sha256_update_fu_279_p_read4;
reg   [31:0] grp_sha256_update_fu_279_p_read5;
reg   [31:0] grp_sha256_update_fu_279_p_read6;
reg   [31:0] grp_sha256_update_fu_279_p_read7;
reg   [31:0] grp_sha256_update_fu_279_p_read8;
reg   [31:0] grp_sha256_update_fu_279_p_read9;
reg   [31:0] grp_sha256_update_fu_279_p_read10;
wire   [5:0] grp_sha256_update_fu_279_data_address0;
wire    grp_sha256_update_fu_279_data_ce0;
reg   [31:0] grp_sha256_update_fu_279_len;
wire   [31:0] grp_sha256_update_fu_279_ap_return_0;
wire   [31:0] grp_sha256_update_fu_279_ap_return_1;
wire   [31:0] grp_sha256_update_fu_279_ap_return_2;
wire   [31:0] grp_sha256_update_fu_279_ap_return_3;
wire   [31:0] grp_sha256_update_fu_279_ap_return_4;
wire   [31:0] grp_sha256_update_fu_279_ap_return_5;
wire   [31:0] grp_sha256_update_fu_279_ap_return_6;
wire   [31:0] grp_sha256_update_fu_279_ap_return_7;
wire   [31:0] grp_sha256_update_fu_279_ap_return_8;
wire   [31:0] grp_sha256_update_fu_279_ap_return_9;
wire   [31:0] grp_sha256_update_fu_279_ap_return_10;
reg   [6:0] i9_reg_225;
wire    ap_CS_fsm_state4;
reg   [5:0] i_1_reg_237;
wire    ap_CS_fsm_state7;
reg   [5:0] i_2_reg_249;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state10;
reg    ap_reg_grp_sha256_final_fu_260_ap_start;
reg    ap_reg_grp_sha256_update_fu_279_ap_start;
wire    ap_CS_fsm_state5;
wire   [63:0] sum_cast_fu_647_p1;
wire   [63:0] tmp_116_fu_662_p1;
wire   [63:0] sum2_cast_fu_707_p1;
wire   [63:0] tmp_115_fu_717_p1;
reg   [31:0] n_fu_94;
wire   [31:0] n_1_fu_652_p2;
reg   [31:0] sha256ctx_datalen_fu_98;
reg    ap_block_state5_on_subcall_done;
reg   [31:0] sha256ctx_bitlen_0_2_fu_102;
reg   [31:0] sha256ctx_bitlen_1_2_fu_106;
reg   [31:0] sha256ctx_state_0_2_fu_110;
reg   [31:0] sha256ctx_state_1_2_fu_114;
reg   [31:0] sha256ctx_state_2_2_fu_118;
reg   [31:0] sha256ctx_state_3_2_fu_122;
reg   [31:0] sha256ctx_state_4_2_fu_126;
reg   [31:0] sha256ctx_state_5_2_fu_130;
reg   [31:0] sha256ctx_state_6_2_fu_134;
reg   [31:0] sha256ctx_state_7_2_fu_138;
reg   [31:0] seg_offset_fu_142;
wire   [31:0] seg_offset_1_fu_667_p2;
wire   [25:0] tmp_124_fu_601_p4;
wire   [9:0] tmp_144_cast_fu_633_p1;
wire   [9:0] tmp1_fu_637_p2;
wire   [9:0] sum_fu_642_p2;
wire   [31:0] i_1_cast_fu_678_p1;
wire   [9:0] tmp_145_cast_fu_693_p1;
wire   [9:0] tmp2_fu_697_p2;
wire   [9:0] sum2_fu_702_p2;
reg   [9:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
#0 ap_reg_grp_sha256_final_fu_260_ap_start = 1'b0;
#0 ap_reg_grp_sha256_update_fu_279_ap_start = 1'b0;
end

sha256_AXILiteS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_AXILITES_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_AXILITES_DATA_WIDTH ))
sha256_AXILiteS_s_axi_U(
    .AWVALID(s_axi_AXILiteS_AWVALID),
    .AWREADY(s_axi_AXILiteS_AWREADY),
    .AWADDR(s_axi_AXILiteS_AWADDR),
    .WVALID(s_axi_AXILiteS_WVALID),
    .WREADY(s_axi_AXILiteS_WREADY),
    .WDATA(s_axi_AXILiteS_WDATA),
    .WSTRB(s_axi_AXILiteS_WSTRB),
    .ARVALID(s_axi_AXILiteS_ARVALID),
    .ARREADY(s_axi_AXILiteS_ARREADY),
    .ARADDR(s_axi_AXILiteS_ARADDR),
    .RVALID(s_axi_AXILiteS_RVALID),
    .RREADY(s_axi_AXILiteS_RREADY),
    .RDATA(s_axi_AXILiteS_RDATA),
    .RRESP(s_axi_AXILiteS_RRESP),
    .BVALID(s_axi_AXILiteS_BVALID),
    .BREADY(s_axi_AXILiteS_BREADY),
    .BRESP(s_axi_AXILiteS_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .data_address0(data_address0),
    .data_ce0(data_ce0),
    .data_q0(data_q0),
    .base_offset(base_offset),
    .bytes(bytes),
    .digest_address0(digest_address0),
    .digest_ce0(digest_ce0),
    .digest_we0(digest_we0),
    .digest_d0(seg_buf_q0)
);

sha256_seg_buf #(
    .DataWidth( 8 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
seg_buf_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(seg_buf_address0),
    .ce0(seg_buf_ce0),
    .we0(seg_buf_we0),
    .d0(seg_buf_d0),
    .q0(seg_buf_q0),
    .address1(grp_sha256_final_fu_260_hash_address1),
    .ce1(seg_buf_ce1),
    .we1(seg_buf_we1),
    .d1(grp_sha256_final_fu_260_hash_d1)
);

sha256_sha256ctx_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
sha256ctx_data_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(sha256ctx_data_address0),
    .ce0(sha256ctx_data_ce0),
    .we0(sha256ctx_data_we0),
    .d0(sha256ctx_data_d0),
    .q0(sha256ctx_data_q0),
    .address1(sha256ctx_data_address1),
    .ce1(sha256ctx_data_ce1),
    .we1(sha256ctx_data_we1),
    .d1(grp_sha256_final_fu_260_ctx_data_d1),
    .q1(sha256ctx_data_q1)
);

sha256_final grp_sha256_final_fu_260(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_sha256_final_fu_260_ap_start),
    .ap_done(grp_sha256_final_fu_260_ap_done),
    .ap_idle(grp_sha256_final_fu_260_ap_idle),
    .ap_ready(grp_sha256_final_fu_260_ap_ready),
    .ctx_data_address0(grp_sha256_final_fu_260_ctx_data_address0),
    .ctx_data_ce0(grp_sha256_final_fu_260_ctx_data_ce0),
    .ctx_data_we0(grp_sha256_final_fu_260_ctx_data_we0),
    .ctx_data_d0(grp_sha256_final_fu_260_ctx_data_d0),
    .ctx_data_q0(sha256ctx_data_q0),
    .ctx_data_address1(grp_sha256_final_fu_260_ctx_data_address1),
    .ctx_data_ce1(grp_sha256_final_fu_260_ctx_data_ce1),
    .ctx_data_we1(grp_sha256_final_fu_260_ctx_data_we1),
    .ctx_data_d1(grp_sha256_final_fu_260_ctx_data_d1),
    .ctx_data_q1(sha256ctx_data_q1),
    .ctx_datalen_read(reg_457),
    .ctx_bitlen_0_read(reg_463),
    .p_read3(reg_469),
    .p_read1(reg_475),
    .p_read2(reg_481),
    .p_read4(reg_487),
    .p_read5(reg_493),
    .p_read6(reg_499),
    .p_read7(reg_505),
    .p_read8(reg_511),
    .p_read9(reg_517),
    .hash_address0(grp_sha256_final_fu_260_hash_address0),
    .hash_ce0(grp_sha256_final_fu_260_hash_ce0),
    .hash_we0(grp_sha256_final_fu_260_hash_we0),
    .hash_d0(grp_sha256_final_fu_260_hash_d0),
    .hash_address1(grp_sha256_final_fu_260_hash_address1),
    .hash_ce1(grp_sha256_final_fu_260_hash_ce1),
    .hash_we1(grp_sha256_final_fu_260_hash_we1),
    .hash_d1(grp_sha256_final_fu_260_hash_d1)
);

sha256_update grp_sha256_update_fu_279(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_sha256_update_fu_279_ap_start),
    .ap_done(grp_sha256_update_fu_279_ap_done),
    .ap_idle(grp_sha256_update_fu_279_ap_idle),
    .ap_ready(grp_sha256_update_fu_279_ap_ready),
    .ctx_data_address0(grp_sha256_update_fu_279_ctx_data_address0),
    .ctx_data_ce0(grp_sha256_update_fu_279_ctx_data_ce0),
    .ctx_data_we0(grp_sha256_update_fu_279_ctx_data_we0),
    .ctx_data_d0(grp_sha256_update_fu_279_ctx_data_d0),
    .ctx_data_q0(sha256ctx_data_q0),
    .ctx_data_address1(grp_sha256_update_fu_279_ctx_data_address1),
    .ctx_data_ce1(grp_sha256_update_fu_279_ctx_data_ce1),
    .ctx_data_q1(sha256ctx_data_q1),
    .ctx_datalen_read(grp_sha256_update_fu_279_ctx_datalen_read),
    .p_read1(grp_sha256_update_fu_279_p_read1),
    .p_read2(grp_sha256_update_fu_279_p_read2),
    .p_read3(grp_sha256_update_fu_279_p_read3),
    .p_read4(grp_sha256_update_fu_279_p_read4),
    .p_read5(grp_sha256_update_fu_279_p_read5),
    .p_read6(grp_sha256_update_fu_279_p_read6),
    .p_read7(grp_sha256_update_fu_279_p_read7),
    .p_read8(grp_sha256_update_fu_279_p_read8),
    .p_read9(grp_sha256_update_fu_279_p_read9),
    .p_read10(grp_sha256_update_fu_279_p_read10),
    .data_address0(grp_sha256_update_fu_279_data_address0),
    .data_ce0(grp_sha256_update_fu_279_data_ce0),
    .data_q0(seg_buf_q0),
    .len(grp_sha256_update_fu_279_len),
    .ap_return_0(grp_sha256_update_fu_279_ap_return_0),
    .ap_return_1(grp_sha256_update_fu_279_ap_return_1),
    .ap_return_2(grp_sha256_update_fu_279_ap_return_2),
    .ap_return_3(grp_sha256_update_fu_279_ap_return_3),
    .ap_return_4(grp_sha256_update_fu_279_ap_return_4),
    .ap_return_5(grp_sha256_update_fu_279_ap_return_5),
    .ap_return_6(grp_sha256_update_fu_279_ap_return_6),
    .ap_return_7(grp_sha256_update_fu_279_ap_return_7),
    .ap_return_8(grp_sha256_update_fu_279_ap_return_8),
    .ap_return_9(grp_sha256_update_fu_279_ap_return_9),
    .ap_return_10(grp_sha256_update_fu_279_ap_return_10)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_grp_sha256_final_fu_260_ap_start <= 1'b0;
    end else begin
        if (((tmp_s_fu_595_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_reg_grp_sha256_final_fu_260_ap_start <= 1'b1;
        end else if ((grp_sha256_final_fu_260_ap_ready == 1'b1)) begin
            ap_reg_grp_sha256_final_fu_260_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_grp_sha256_update_fu_279_ap_start <= 1'b0;
    end else begin
        if ((((exitcond5_fu_621_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3)) | ((exitcond4_fu_682_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6)))) begin
            ap_reg_grp_sha256_update_fu_279_ap_start <= 1'b1;
        end else if ((grp_sha256_update_fu_279_ap_ready == 1'b1)) begin
            ap_reg_grp_sha256_update_fu_279_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_fu_595_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (icmp_fu_611_p2 == 1'd0))) begin
        i9_reg_225 <= 7'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        i9_reg_225 <= i_7_reg_860;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_fu_611_p2 == 1'd1) & (tmp_s_fu_595_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i_1_reg_237 <= 6'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        i_1_reg_237 <= i_8_reg_873;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        i_2_reg_249 <= i_reg_941;
    end else if (((grp_sha256_final_fu_260_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        i_2_reg_249 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond4_fu_682_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        n_fu_94 <= 32'd0;
    end else if (((exitcond5_fu_621_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        n_fu_94 <= n_1_fu_652_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        n_fu_94 <= bytes;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5) & (icmp_reg_847 == 1'd0))) begin
        seg_offset_fu_142 <= seg_offset_1_fu_667_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        seg_offset_fu_142 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_reg_847 == 1'd1) & (1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5)) | ((1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5) & (icmp_reg_847 == 1'd0)))) begin
        sha256ctx_bitlen_0_2_fu_102 <= grp_sha256_update_fu_279_ap_return_1;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        sha256ctx_bitlen_0_2_fu_102 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_reg_847 == 1'd1) & (1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5)) | ((1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5) & (icmp_reg_847 == 1'd0)))) begin
        sha256ctx_bitlen_1_2_fu_106 <= grp_sha256_update_fu_279_ap_return_2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        sha256ctx_bitlen_1_2_fu_106 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_reg_847 == 1'd1) & (1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5)) | ((1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5) & (icmp_reg_847 == 1'd0)))) begin
        sha256ctx_datalen_fu_98 <= grp_sha256_update_fu_279_ap_return_0;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        sha256ctx_datalen_fu_98 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_reg_847 == 1'd1) & (1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5)) | ((1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5) & (icmp_reg_847 == 1'd0)))) begin
        sha256ctx_state_0_2_fu_110 <= grp_sha256_update_fu_279_ap_return_3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        sha256ctx_state_0_2_fu_110 <= 32'd1779033703;
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_reg_847 == 1'd1) & (1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5)) | ((1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5) & (icmp_reg_847 == 1'd0)))) begin
        sha256ctx_state_1_2_fu_114 <= grp_sha256_update_fu_279_ap_return_4;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        sha256ctx_state_1_2_fu_114 <= 32'd3144134277;
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_reg_847 == 1'd1) & (1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5)) | ((1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5) & (icmp_reg_847 == 1'd0)))) begin
        sha256ctx_state_2_2_fu_118 <= grp_sha256_update_fu_279_ap_return_5;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        sha256ctx_state_2_2_fu_118 <= 32'd1013904242;
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_reg_847 == 1'd1) & (1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5)) | ((1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5) & (icmp_reg_847 == 1'd0)))) begin
        sha256ctx_state_3_2_fu_122 <= grp_sha256_update_fu_279_ap_return_6;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        sha256ctx_state_3_2_fu_122 <= 32'd2773480762;
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_reg_847 == 1'd1) & (1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5)) | ((1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5) & (icmp_reg_847 == 1'd0)))) begin
        sha256ctx_state_4_2_fu_126 <= grp_sha256_update_fu_279_ap_return_7;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        sha256ctx_state_4_2_fu_126 <= 32'd1359893119;
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_reg_847 == 1'd1) & (1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5)) | ((1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5) & (icmp_reg_847 == 1'd0)))) begin
        sha256ctx_state_5_2_fu_130 <= grp_sha256_update_fu_279_ap_return_8;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        sha256ctx_state_5_2_fu_130 <= 32'd2600822924;
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_reg_847 == 1'd1) & (1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5)) | ((1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5) & (icmp_reg_847 == 1'd0)))) begin
        sha256ctx_state_6_2_fu_134 <= grp_sha256_update_fu_279_ap_return_9;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        sha256ctx_state_6_2_fu_134 <= 32'd528734635;
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_reg_847 == 1'd1) & (1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5)) | ((1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5) & (icmp_reg_847 == 1'd0)))) begin
        sha256ctx_state_7_2_fu_138 <= grp_sha256_update_fu_279_ap_return_10;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        sha256ctx_state_7_2_fu_138 <= 32'd1541459225;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_7_reg_860 <= i_7_fu_627_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        i_8_reg_873 <= i_8_fu_687_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        i_reg_941 <= i_fu_728_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_fu_595_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        icmp_reg_847 <= icmp_fu_611_p2;
        tmp_125_reg_851 <= tmp_125_fu_617_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        n_load_reg_837 <= n_fu_94;
    end
end

always @ (posedge ap_clk) begin
    if ((((exitcond5_fu_621_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3)) | ((tmp_s_fu_595_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        reg_457 <= sha256ctx_datalen_fu_98;
        reg_463 <= sha256ctx_bitlen_0_2_fu_102;
        reg_469 <= sha256ctx_bitlen_1_2_fu_106;
        reg_475 <= sha256ctx_state_0_2_fu_110;
        reg_481 <= sha256ctx_state_1_2_fu_114;
        reg_487 <= sha256ctx_state_2_2_fu_118;
        reg_493 <= sha256ctx_state_3_2_fu_122;
        reg_499 <= sha256ctx_state_4_2_fu_126;
        reg_505 <= sha256ctx_state_5_2_fu_130;
        reg_511 <= sha256ctx_state_6_2_fu_134;
        reg_517 <= sha256ctx_state_7_2_fu_138;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond4_fu_682_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        sha256ctx_bitlen_0_1_reg_888 <= sha256ctx_bitlen_0_2_fu_102;
        sha256ctx_bitlen_1_1_reg_893 <= sha256ctx_bitlen_1_2_fu_106;
        sha256ctx_datalen_lo_1_reg_883 <= sha256ctx_datalen_fu_98;
        sha256ctx_state_0_2_2_reg_898 <= sha256ctx_state_0_2_fu_110;
        sha256ctx_state_1_2_2_reg_903 <= sha256ctx_state_1_2_fu_114;
        sha256ctx_state_2_2_2_reg_908 <= sha256ctx_state_2_2_fu_118;
        sha256ctx_state_3_2_2_reg_913 <= sha256ctx_state_3_2_fu_122;
        sha256ctx_state_4_2_2_reg_918 <= sha256ctx_state_4_2_fu_126;
        sha256ctx_state_5_2_2_reg_923 <= sha256ctx_state_5_2_fu_130;
        sha256ctx_state_6_2_2_reg_928 <= sha256ctx_state_6_2_fu_134;
        sha256ctx_state_7_2_2_reg_933 <= sha256ctx_state_7_2_fu_138;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (exitcond_fu_722_p2 == 1'd0))) begin
        tmp_114_reg_946[5 : 0] <= tmp_114_fu_734_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        tmp_reg_831 <= tmp_fu_523_p1;
    end
end

always @ (*) begin
    if (((exitcond_fu_722_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_fu_722_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        data_address0 = sum2_cast_fu_707_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        data_address0 = sum_cast_fu_647_p1;
    end else begin
        data_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state6))) begin
        data_ce0 = 1'b1;
    end else begin
        data_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        digest_ce0 = 1'b1;
    end else begin
        digest_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        digest_we0 = 1'b1;
    end else begin
        digest_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        if ((icmp_reg_847 == 1'd1)) begin
            grp_sha256_update_fu_279_ctx_datalen_read = sha256ctx_datalen_lo_1_reg_883;
        end else if ((icmp_reg_847 == 1'd0)) begin
            grp_sha256_update_fu_279_ctx_datalen_read = reg_457;
        end else begin
            grp_sha256_update_fu_279_ctx_datalen_read = 'bx;
        end
    end else begin
        grp_sha256_update_fu_279_ctx_datalen_read = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        if ((icmp_reg_847 == 1'd1)) begin
            grp_sha256_update_fu_279_len = n_load_reg_837;
        end else if ((icmp_reg_847 == 1'd0)) begin
            grp_sha256_update_fu_279_len = 32'd64;
        end else begin
            grp_sha256_update_fu_279_len = 'bx;
        end
    end else begin
        grp_sha256_update_fu_279_len = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        if ((icmp_reg_847 == 1'd1)) begin
            grp_sha256_update_fu_279_p_read1 = sha256ctx_bitlen_0_1_reg_888;
        end else if ((icmp_reg_847 == 1'd0)) begin
            grp_sha256_update_fu_279_p_read1 = reg_463;
        end else begin
            grp_sha256_update_fu_279_p_read1 = 'bx;
        end
    end else begin
        grp_sha256_update_fu_279_p_read1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        if ((icmp_reg_847 == 1'd1)) begin
            grp_sha256_update_fu_279_p_read10 = sha256ctx_state_7_2_2_reg_933;
        end else if ((icmp_reg_847 == 1'd0)) begin
            grp_sha256_update_fu_279_p_read10 = reg_517;
        end else begin
            grp_sha256_update_fu_279_p_read10 = 'bx;
        end
    end else begin
        grp_sha256_update_fu_279_p_read10 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        if ((icmp_reg_847 == 1'd1)) begin
            grp_sha256_update_fu_279_p_read2 = sha256ctx_bitlen_1_1_reg_893;
        end else if ((icmp_reg_847 == 1'd0)) begin
            grp_sha256_update_fu_279_p_read2 = reg_469;
        end else begin
            grp_sha256_update_fu_279_p_read2 = 'bx;
        end
    end else begin
        grp_sha256_update_fu_279_p_read2 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        if ((icmp_reg_847 == 1'd1)) begin
            grp_sha256_update_fu_279_p_read3 = sha256ctx_state_0_2_2_reg_898;
        end else if ((icmp_reg_847 == 1'd0)) begin
            grp_sha256_update_fu_279_p_read3 = reg_475;
        end else begin
            grp_sha256_update_fu_279_p_read3 = 'bx;
        end
    end else begin
        grp_sha256_update_fu_279_p_read3 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        if ((icmp_reg_847 == 1'd1)) begin
            grp_sha256_update_fu_279_p_read4 = sha256ctx_state_1_2_2_reg_903;
        end else if ((icmp_reg_847 == 1'd0)) begin
            grp_sha256_update_fu_279_p_read4 = reg_481;
        end else begin
            grp_sha256_update_fu_279_p_read4 = 'bx;
        end
    end else begin
        grp_sha256_update_fu_279_p_read4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        if ((icmp_reg_847 == 1'd1)) begin
            grp_sha256_update_fu_279_p_read5 = sha256ctx_state_2_2_2_reg_908;
        end else if ((icmp_reg_847 == 1'd0)) begin
            grp_sha256_update_fu_279_p_read5 = reg_487;
        end else begin
            grp_sha256_update_fu_279_p_read5 = 'bx;
        end
    end else begin
        grp_sha256_update_fu_279_p_read5 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        if ((icmp_reg_847 == 1'd1)) begin
            grp_sha256_update_fu_279_p_read6 = sha256ctx_state_3_2_2_reg_913;
        end else if ((icmp_reg_847 == 1'd0)) begin
            grp_sha256_update_fu_279_p_read6 = reg_493;
        end else begin
            grp_sha256_update_fu_279_p_read6 = 'bx;
        end
    end else begin
        grp_sha256_update_fu_279_p_read6 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        if ((icmp_reg_847 == 1'd1)) begin
            grp_sha256_update_fu_279_p_read7 = sha256ctx_state_4_2_2_reg_918;
        end else if ((icmp_reg_847 == 1'd0)) begin
            grp_sha256_update_fu_279_p_read7 = reg_499;
        end else begin
            grp_sha256_update_fu_279_p_read7 = 'bx;
        end
    end else begin
        grp_sha256_update_fu_279_p_read7 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        if ((icmp_reg_847 == 1'd1)) begin
            grp_sha256_update_fu_279_p_read8 = sha256ctx_state_5_2_2_reg_923;
        end else if ((icmp_reg_847 == 1'd0)) begin
            grp_sha256_update_fu_279_p_read8 = reg_505;
        end else begin
            grp_sha256_update_fu_279_p_read8 = 'bx;
        end
    end else begin
        grp_sha256_update_fu_279_p_read8 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        if ((icmp_reg_847 == 1'd1)) begin
            grp_sha256_update_fu_279_p_read9 = sha256ctx_state_6_2_2_reg_928;
        end else if ((icmp_reg_847 == 1'd0)) begin
            grp_sha256_update_fu_279_p_read9 = reg_511;
        end else begin
            grp_sha256_update_fu_279_p_read9 = 'bx;
        end
    end else begin
        grp_sha256_update_fu_279_p_read9 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        seg_buf_address0 = tmp_114_fu_734_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        seg_buf_address0 = tmp_115_fu_717_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        seg_buf_address0 = tmp_116_fu_662_p1;
    end else if ((((icmp_reg_847 == 1'd1) & (1'b1 == ap_CS_fsm_state5)) | ((1'b1 == ap_CS_fsm_state5) & (icmp_reg_847 == 1'd0)))) begin
        seg_buf_address0 = grp_sha256_update_fu_279_data_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        seg_buf_address0 = grp_sha256_final_fu_260_hash_address0;
    end else begin
        seg_buf_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state9))) begin
        seg_buf_ce0 = 1'b1;
    end else if ((((icmp_reg_847 == 1'd1) & (1'b1 == ap_CS_fsm_state5)) | ((1'b1 == ap_CS_fsm_state5) & (icmp_reg_847 == 1'd0)))) begin
        seg_buf_ce0 = grp_sha256_update_fu_279_data_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        seg_buf_ce0 = grp_sha256_final_fu_260_hash_ce0;
    end else begin
        seg_buf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        seg_buf_ce1 = grp_sha256_final_fu_260_hash_ce1;
    end else begin
        seg_buf_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state4))) begin
        seg_buf_d0 = data_q0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        seg_buf_d0 = grp_sha256_final_fu_260_hash_d0;
    end else begin
        seg_buf_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state4))) begin
        seg_buf_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        seg_buf_we0 = grp_sha256_final_fu_260_hash_we0;
    end else begin
        seg_buf_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        seg_buf_we1 = grp_sha256_final_fu_260_hash_we1;
    end else begin
        seg_buf_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_reg_847 == 1'd1) & (1'b1 == ap_CS_fsm_state5)) | ((1'b1 == ap_CS_fsm_state5) & (icmp_reg_847 == 1'd0)))) begin
        sha256ctx_data_address0 = grp_sha256_update_fu_279_ctx_data_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        sha256ctx_data_address0 = grp_sha256_final_fu_260_ctx_data_address0;
    end else begin
        sha256ctx_data_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_reg_847 == 1'd1) & (1'b1 == ap_CS_fsm_state5)) | ((1'b1 == ap_CS_fsm_state5) & (icmp_reg_847 == 1'd0)))) begin
        sha256ctx_data_address1 = grp_sha256_update_fu_279_ctx_data_address1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        sha256ctx_data_address1 = grp_sha256_final_fu_260_ctx_data_address1;
    end else begin
        sha256ctx_data_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_reg_847 == 1'd1) & (1'b1 == ap_CS_fsm_state5)) | ((1'b1 == ap_CS_fsm_state5) & (icmp_reg_847 == 1'd0)))) begin
        sha256ctx_data_ce0 = grp_sha256_update_fu_279_ctx_data_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        sha256ctx_data_ce0 = grp_sha256_final_fu_260_ctx_data_ce0;
    end else begin
        sha256ctx_data_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_reg_847 == 1'd1) & (1'b1 == ap_CS_fsm_state5)) | ((1'b1 == ap_CS_fsm_state5) & (icmp_reg_847 == 1'd0)))) begin
        sha256ctx_data_ce1 = grp_sha256_update_fu_279_ctx_data_ce1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        sha256ctx_data_ce1 = grp_sha256_final_fu_260_ctx_data_ce1;
    end else begin
        sha256ctx_data_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_reg_847 == 1'd1) & (1'b1 == ap_CS_fsm_state5)) | ((1'b1 == ap_CS_fsm_state5) & (icmp_reg_847 == 1'd0)))) begin
        sha256ctx_data_d0 = grp_sha256_update_fu_279_ctx_data_d0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        sha256ctx_data_d0 = grp_sha256_final_fu_260_ctx_data_d0;
    end else begin
        sha256ctx_data_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_reg_847 == 1'd1) & (1'b1 == ap_CS_fsm_state5)) | ((1'b1 == ap_CS_fsm_state5) & (icmp_reg_847 == 1'd0)))) begin
        sha256ctx_data_we0 = grp_sha256_update_fu_279_ctx_data_we0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        sha256ctx_data_we0 = grp_sha256_final_fu_260_ctx_data_we0;
    end else begin
        sha256ctx_data_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        sha256ctx_data_we1 = grp_sha256_final_fu_260_ctx_data_we1;
    end else begin
        sha256ctx_data_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_fu_611_p2 == 1'd1) & (tmp_s_fu_595_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else if (((tmp_s_fu_595_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (icmp_fu_611_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((exitcond5_fu_621_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (exitcond4_fu_682_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state8 : begin
            if (((grp_sha256_final_fu_260_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((exitcond_fu_722_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state5_on_subcall_done = (((icmp_reg_847 == 1'd1) & (grp_sha256_update_fu_279_ap_done == 1'b0)) | ((grp_sha256_update_fu_279_ap_done == 1'b0) & (icmp_reg_847 == 1'd0)));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign digest_address0 = tmp_114_reg_946;

assign exitcond4_fu_682_p2 = ((i_1_cast_fu_678_p1 == n_load_reg_837) ? 1'b1 : 1'b0);

assign exitcond5_fu_621_p2 = ((i9_reg_225 == 7'd64) ? 1'b1 : 1'b0);

assign exitcond_fu_722_p2 = ((i_2_reg_249 == 6'd32) ? 1'b1 : 1'b0);

assign grp_sha256_final_fu_260_ap_start = ap_reg_grp_sha256_final_fu_260_ap_start;

assign grp_sha256_update_fu_279_ap_start = ap_reg_grp_sha256_update_fu_279_ap_start;

assign i_1_cast_fu_678_p1 = i_1_reg_237;

assign i_7_fu_627_p2 = (i9_reg_225 + 7'd1);

assign i_8_fu_687_p2 = (i_1_reg_237 + 6'd1);

assign i_fu_728_p2 = (i_2_reg_249 + 6'd1);

assign icmp_fu_611_p2 = ((tmp_124_fu_601_p4 == 26'd0) ? 1'b1 : 1'b0);

assign n_1_fu_652_p2 = ($signed(n_load_reg_837) + $signed(32'd4294967232));

assign seg_offset_1_fu_667_p2 = (seg_offset_fu_142 + 32'd64);

assign sum2_cast_fu_707_p1 = sum2_fu_702_p2;

assign sum2_fu_702_p2 = (tmp2_fu_697_p2 + tmp_reg_831);

assign sum_cast_fu_647_p1 = sum_fu_642_p2;

assign sum_fu_642_p2 = (tmp1_fu_637_p2 + tmp_reg_831);

assign tmp1_fu_637_p2 = (tmp_125_reg_851 + tmp_144_cast_fu_633_p1);

assign tmp2_fu_697_p2 = (tmp_125_reg_851 + tmp_145_cast_fu_693_p1);

assign tmp_114_fu_734_p1 = i_2_reg_249;

assign tmp_115_fu_717_p1 = i_1_reg_237;

assign tmp_116_fu_662_p1 = i9_reg_225;

assign tmp_124_fu_601_p4 = {{n_fu_94[31:6]}};

assign tmp_125_fu_617_p1 = seg_offset_fu_142[9:0];

assign tmp_144_cast_fu_633_p1 = i9_reg_225;

assign tmp_145_cast_fu_693_p1 = i_1_reg_237;

assign tmp_fu_523_p1 = base_offset[9:0];

assign tmp_s_fu_595_p2 = ((n_fu_94 == 32'd0) ? 1'b1 : 1'b0);

always @ (posedge ap_clk) begin
    tmp_114_reg_946[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
end

endmodule //sha256
