# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/sha256_acc2/acc2/acc2.srcs/sources_1/bd/hw_acc/ip/hw_acc_sha256_0_0/hw_acc_sha256_0_0.xci
# IP: The module: 'hw_acc_sha256_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/sha256_acc2/acc2/acc2.srcs/sources_1/bd/hw_acc/ip/hw_acc_sha256_0_0/constraints/sha256_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_acc_sha256_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/sha256_acc2/acc2/acc2.srcs/sources_1/bd/hw_acc/ip/hw_acc_sha256_0_0/hw_acc_sha256_0_0.xci
# IP: The module: 'hw_acc_sha256_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/sha256_acc2/acc2/acc2.srcs/sources_1/bd/hw_acc/ip/hw_acc_sha256_0_0/constraints/sha256_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_acc_sha256_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
